server:
  port: 9192
spring:
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: order-service
  config:
    import: http://localhost:9196/
#logging:
#  file: C:/Users/Basant.Hota/Desktop/oms.log